### ISSUE TITLE
New operator definitions

### ISSUE THREAD

**Issue by jm9e** [Bitspark/slang#87]
See #82 and #83 

**Proposal for new operator definitions**
```YAML
in:
  type: number
out:
  type: number
delegates:
  delegate1:
    in:
      type: number
    out:
      type: number
properties:
  - prop1

operators:
  op1:
    operator: opName1
  op2:
    operator: opName2
    properties:
      prop: $prop1

connections:
  (:
    - (op1
  op1):
    - (delegate1
  delegate1):
    - (op2
  op2):
    - )
```

**Changes**
* Add `delegates` for wiring out delegate ports
* Add `properties` for allowing to specify properties when instancing
* Allow usage of property values prefixed with `$` to indicate usage of property variables specified in `properties`
